version: '3.6'
services:
  app:
    container_name: app
    build: ./app
    restart: always
    ports:
      - 80:8000
    volumes:
      - ./app/static:/app/static
      - ./app/templates:/app/templates

  airflow:
    container_name: airflow
    build: ./airflow
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./airflow/modules:/usr/local/airflow/modules

  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: ./dockerfile
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - JDA

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.1
    container_name: kibana
    restart: always
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
    depends_on:
      - elasticsearch
    networks:
      - JDA
  
  mongo:
    container_name: mongo
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    command: mongod
    networks:
      - JDA
    
volumes:
  mongo:
  elasticsearch:

networks:
  JDA:
    driver: bridge